//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scenes/CAFE STUFF/Cafe.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Cafe : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Cafe()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Cafe"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""0b580d8c-4e13-4c76-b6a4-a4f9c8abbbd6"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""f35bb4ee-79fa-4729-89ff-2f785a7fa004"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blend"",
                    ""type"": ""Button"",
                    ""id"": ""3366854e-a489-47f0-9393-a439364b2fae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shake"",
                    ""type"": ""Button"",
                    ""id"": ""1785f5c6-0c57-4d52-9987-bf4dacdbc65a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stir"",
                    ""type"": ""Button"",
                    ""id"": ""3caf6c8a-708c-4170-8b3d-b2460cdc6256"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ice"",
                    ""type"": ""Button"",
                    ""id"": ""04b5fc49-6a2d-4035-a171-97bd3c39e32c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Espresso"",
                    ""type"": ""Button"",
                    ""id"": ""01b3c212-7906-487c-ba2e-56dbb43cd6ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Caramel"",
                    ""type"": ""Button"",
                    ""id"": ""79d00f09-20b5-4feb-9d06-ff44c18eaf28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Vanilla"",
                    ""type"": ""Button"",
                    ""id"": ""767f5717-902a-4c10-9eff-17ab860a8333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Peppermint"",
                    ""type"": ""Button"",
                    ""id"": ""59b842f5-84a6-46c1-92c4-504ac1b805f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hazelnut"",
                    ""type"": ""Button"",
                    ""id"": ""68de73f4-5bfe-45a4-a973-afd97486223d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mocha"",
                    ""type"": ""Button"",
                    ""id"": ""575ce2fe-a152-41d5-a11a-d7fcec3b1ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Black Tea"",
                    ""type"": ""Button"",
                    ""id"": ""b4b64c45-73fb-4b30-881b-9af8cf7a961d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Green Tea"",
                    ""type"": ""Button"",
                    ""id"": ""6e18fd1c-e204-432f-9d0e-8f24b7ed4590"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Chai Tea"",
                    ""type"": ""Button"",
                    ""id"": ""bc8adb7f-f602-4050-b429-14b91fc77ea7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Passion Tea"",
                    ""type"": ""Button"",
                    ""id"": ""bacd307f-0454-4f6b-9ebe-b327cc2e3982"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Matcha"",
                    ""type"": ""Button"",
                    ""id"": ""11c137c6-0383-440c-93a6-f6fa91e34c99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whipped Cream"",
                    ""type"": ""Button"",
                    ""id"": ""df65222e-6f92-4b4e-b54c-f2778aff9fec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Creme Base"",
                    ""type"": ""Button"",
                    ""id"": ""438e4c0c-26bf-4989-99f2-019c11646855"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Coffee Base"",
                    ""type"": ""Button"",
                    ""id"": ""082cf36c-46ce-43f2-b543-8f60c6c11990"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whole Milk"",
                    ""type"": ""Button"",
                    ""id"": ""05f22354-1019-4a21-ba5f-f9b0e22cd27d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skim Milk"",
                    ""type"": ""Button"",
                    ""id"": ""bac2f0e6-8028-484a-a569-948e301dc1ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Oat Milk"",
                    ""type"": ""Button"",
                    ""id"": ""2df162be-2af4-467b-9daf-9dfce9261db4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Almond Milk"",
                    ""type"": ""Button"",
                    ""id"": ""50eede87-94f9-4db7-9edc-02e6463e9cd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Java Chips"",
                    ""type"": ""Button"",
                    ""id"": ""49c9c3a2-6e7b-408e-8489-e7ba34e6194c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprinkles"",
                    ""type"": ""Button"",
                    ""id"": ""0054b7f6-ad9c-4b9d-8b8d-949e463730da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cinnamon"",
                    ""type"": ""Button"",
                    ""id"": ""5bac66eb-6778-4be3-870b-2a7a040aefef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Caramel Drizzle"",
                    ""type"": ""Button"",
                    ""id"": ""d65f1a2f-d7a9-4123-a2f9-18ab77ec5629"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cherry"",
                    ""type"": ""Button"",
                    ""id"": ""a069113a-07cf-4c6c-8547-fde458b6c979"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Frappucino"",
                    ""type"": ""Button"",
                    ""id"": ""62537e89-7a91-43cc-90d8-e3d9dc4f56fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hot"",
                    ""type"": ""Button"",
                    ""id"": ""fc4a3486-fc4e-4615-85af-8a13b0c1da37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Iced"",
                    ""type"": ""Button"",
                    ""id"": ""2d7041c1-ef7a-48e6-bcd8-5bc1ac6b7400"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""946a4ce3-0a9e-4a7d-a776-df4c91cc77b1"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15c2831c-a3f4-4ec9-b84d-99559666e82c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a54a121-06ee-445b-b1c6-a72f18adeb1c"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8312fa5f-a9ec-4fae-af9e-c2794fe0cda9"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Ice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12604d43-6bf2-49d5-bccb-59df383150a0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Espresso"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90d75569-55e7-422b-9991-d2d86ea0a04c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Caramel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c95d7eea-1960-49af-b891-177ccd722a6c"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Vanilla"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73458179-b697-4162-ba50-4fff1138680a"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Peppermint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f4453fe-1cfc-46b6-b13e-d57ba7b9deb6"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Hazelnut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6763e27-1b9c-4dee-bfc0-2a2ce41dea32"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Mocha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26f09049-85ea-4cfe-9038-72d829e83f93"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Black Tea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a03449a4-8de7-4a0c-a9bd-e420fb80a4b6"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Green Tea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d3a1c5e-5a72-4cbb-8d39-3a4a617b512e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Chai Tea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcb6184d-aa77-4ef7-b76f-50ffac42dea1"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Passion Tea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db90c3cb-642e-4772-b0a7-53348ddd008b"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Matcha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b6e6938-96cd-4f84-955b-15c09beddcb4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Whipped Cream"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a519e507-b741-4ed8-9654-0cd11bdd9ee0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Creme Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50dc7cd4-7e51-4358-a9de-dd22192b7650"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Coffee Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31de4424-e3f4-44b2-a477-5451cd29788b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Whole Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0954211-4d51-44ad-9e5b-435e3e235e01"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Skim Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4314379-8d2a-4147-8b33-9e3f04a360e0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Oat Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17730c3c-ffae-4260-8751-1629a7686043"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Almond Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a6bd25f-3e3a-494f-a365-01bb18c6bafd"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Java Chips"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9567bc2-db60-4a6d-bd87-d8740e939ddc"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Sprinkles"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3bca289b-3f49-443f-b78d-8227a4fac371"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Cinnamon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ff273ca-d267-4f77-9120-074421c01c35"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Caramel Drizzle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f9f6c54-206f-4230-a5cf-07a91573f87d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Cherry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d06184f-a8bc-4360-bc05-ec8810617be5"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Frappucino"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9927a5ae-9193-490f-9114-1d35deb9fbe9"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Hot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69a2fbbd-4657-4c6a-9a2e-4f8163d64cad"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Iced"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""545912fc-fa53-4513-a122-9b2d941f48a4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard and mouse"",
            ""bindingGroup"": ""keyboard and mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // player
        m_player = asset.FindActionMap("player", throwIfNotFound: true);
        m_player_Start = m_player.FindAction("Start", throwIfNotFound: true);
        m_player_Blend = m_player.FindAction("Blend", throwIfNotFound: true);
        m_player_Shake = m_player.FindAction("Shake", throwIfNotFound: true);
        m_player_Stir = m_player.FindAction("Stir", throwIfNotFound: true);
        m_player_Ice = m_player.FindAction("Ice", throwIfNotFound: true);
        m_player_Espresso = m_player.FindAction("Espresso", throwIfNotFound: true);
        m_player_Caramel = m_player.FindAction("Caramel", throwIfNotFound: true);
        m_player_Vanilla = m_player.FindAction("Vanilla", throwIfNotFound: true);
        m_player_Peppermint = m_player.FindAction("Peppermint", throwIfNotFound: true);
        m_player_Hazelnut = m_player.FindAction("Hazelnut", throwIfNotFound: true);
        m_player_Mocha = m_player.FindAction("Mocha", throwIfNotFound: true);
        m_player_BlackTea = m_player.FindAction("Black Tea", throwIfNotFound: true);
        m_player_GreenTea = m_player.FindAction("Green Tea", throwIfNotFound: true);
        m_player_ChaiTea = m_player.FindAction("Chai Tea", throwIfNotFound: true);
        m_player_PassionTea = m_player.FindAction("Passion Tea", throwIfNotFound: true);
        m_player_Matcha = m_player.FindAction("Matcha", throwIfNotFound: true);
        m_player_WhippedCream = m_player.FindAction("Whipped Cream", throwIfNotFound: true);
        m_player_CremeBase = m_player.FindAction("Creme Base", throwIfNotFound: true);
        m_player_CoffeeBase = m_player.FindAction("Coffee Base", throwIfNotFound: true);
        m_player_WholeMilk = m_player.FindAction("Whole Milk", throwIfNotFound: true);
        m_player_SkimMilk = m_player.FindAction("Skim Milk", throwIfNotFound: true);
        m_player_OatMilk = m_player.FindAction("Oat Milk", throwIfNotFound: true);
        m_player_AlmondMilk = m_player.FindAction("Almond Milk", throwIfNotFound: true);
        m_player_JavaChips = m_player.FindAction("Java Chips", throwIfNotFound: true);
        m_player_Sprinkles = m_player.FindAction("Sprinkles", throwIfNotFound: true);
        m_player_Cinnamon = m_player.FindAction("Cinnamon", throwIfNotFound: true);
        m_player_CaramelDrizzle = m_player.FindAction("Caramel Drizzle", throwIfNotFound: true);
        m_player_Cherry = m_player.FindAction("Cherry", throwIfNotFound: true);
        m_player_Frappucino = m_player.FindAction("Frappucino", throwIfNotFound: true);
        m_player_Hot = m_player.FindAction("Hot", throwIfNotFound: true);
        m_player_Iced = m_player.FindAction("Iced", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player
    private readonly InputActionMap m_player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_player_Start;
    private readonly InputAction m_player_Blend;
    private readonly InputAction m_player_Shake;
    private readonly InputAction m_player_Stir;
    private readonly InputAction m_player_Ice;
    private readonly InputAction m_player_Espresso;
    private readonly InputAction m_player_Caramel;
    private readonly InputAction m_player_Vanilla;
    private readonly InputAction m_player_Peppermint;
    private readonly InputAction m_player_Hazelnut;
    private readonly InputAction m_player_Mocha;
    private readonly InputAction m_player_BlackTea;
    private readonly InputAction m_player_GreenTea;
    private readonly InputAction m_player_ChaiTea;
    private readonly InputAction m_player_PassionTea;
    private readonly InputAction m_player_Matcha;
    private readonly InputAction m_player_WhippedCream;
    private readonly InputAction m_player_CremeBase;
    private readonly InputAction m_player_CoffeeBase;
    private readonly InputAction m_player_WholeMilk;
    private readonly InputAction m_player_SkimMilk;
    private readonly InputAction m_player_OatMilk;
    private readonly InputAction m_player_AlmondMilk;
    private readonly InputAction m_player_JavaChips;
    private readonly InputAction m_player_Sprinkles;
    private readonly InputAction m_player_Cinnamon;
    private readonly InputAction m_player_CaramelDrizzle;
    private readonly InputAction m_player_Cherry;
    private readonly InputAction m_player_Frappucino;
    private readonly InputAction m_player_Hot;
    private readonly InputAction m_player_Iced;
    public struct PlayerActions
    {
        private @Cafe m_Wrapper;
        public PlayerActions(@Cafe wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start => m_Wrapper.m_player_Start;
        public InputAction @Blend => m_Wrapper.m_player_Blend;
        public InputAction @Shake => m_Wrapper.m_player_Shake;
        public InputAction @Stir => m_Wrapper.m_player_Stir;
        public InputAction @Ice => m_Wrapper.m_player_Ice;
        public InputAction @Espresso => m_Wrapper.m_player_Espresso;
        public InputAction @Caramel => m_Wrapper.m_player_Caramel;
        public InputAction @Vanilla => m_Wrapper.m_player_Vanilla;
        public InputAction @Peppermint => m_Wrapper.m_player_Peppermint;
        public InputAction @Hazelnut => m_Wrapper.m_player_Hazelnut;
        public InputAction @Mocha => m_Wrapper.m_player_Mocha;
        public InputAction @BlackTea => m_Wrapper.m_player_BlackTea;
        public InputAction @GreenTea => m_Wrapper.m_player_GreenTea;
        public InputAction @ChaiTea => m_Wrapper.m_player_ChaiTea;
        public InputAction @PassionTea => m_Wrapper.m_player_PassionTea;
        public InputAction @Matcha => m_Wrapper.m_player_Matcha;
        public InputAction @WhippedCream => m_Wrapper.m_player_WhippedCream;
        public InputAction @CremeBase => m_Wrapper.m_player_CremeBase;
        public InputAction @CoffeeBase => m_Wrapper.m_player_CoffeeBase;
        public InputAction @WholeMilk => m_Wrapper.m_player_WholeMilk;
        public InputAction @SkimMilk => m_Wrapper.m_player_SkimMilk;
        public InputAction @OatMilk => m_Wrapper.m_player_OatMilk;
        public InputAction @AlmondMilk => m_Wrapper.m_player_AlmondMilk;
        public InputAction @JavaChips => m_Wrapper.m_player_JavaChips;
        public InputAction @Sprinkles => m_Wrapper.m_player_Sprinkles;
        public InputAction @Cinnamon => m_Wrapper.m_player_Cinnamon;
        public InputAction @CaramelDrizzle => m_Wrapper.m_player_CaramelDrizzle;
        public InputAction @Cherry => m_Wrapper.m_player_Cherry;
        public InputAction @Frappucino => m_Wrapper.m_player_Frappucino;
        public InputAction @Hot => m_Wrapper.m_player_Hot;
        public InputAction @Iced => m_Wrapper.m_player_Iced;
        public InputActionMap Get() { return m_Wrapper.m_player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Start.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Blend.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Blend.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Blend.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Shake.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShake;
                @Shake.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShake;
                @Shake.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShake;
                @Stir.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStir;
                @Stir.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStir;
                @Stir.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStir;
                @Ice.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Ice.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Ice.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Espresso.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Espresso.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Espresso.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Caramel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Caramel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Caramel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Vanilla.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Vanilla.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Vanilla.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Peppermint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Peppermint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Peppermint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Hazelnut.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Hazelnut.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Hazelnut.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Mocha.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @Mocha.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @Mocha.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @BlackTea.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlackTea;
                @BlackTea.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlackTea;
                @BlackTea.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlackTea;
                @GreenTea.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGreenTea;
                @GreenTea.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGreenTea;
                @GreenTea.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGreenTea;
                @ChaiTea.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChaiTea;
                @ChaiTea.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChaiTea;
                @ChaiTea.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnChaiTea;
                @PassionTea.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPassionTea;
                @PassionTea.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPassionTea;
                @PassionTea.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPassionTea;
                @Matcha.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @Matcha.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @Matcha.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @WhippedCream.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWhippedCream;
                @WhippedCream.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWhippedCream;
                @WhippedCream.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWhippedCream;
                @CremeBase.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CremeBase.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CremeBase.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CoffeeBase.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @CoffeeBase.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @CoffeeBase.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @WholeMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @WholeMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @WholeMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @SkimMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @SkimMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @SkimMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @OatMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @OatMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @OatMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @AlmondMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
                @AlmondMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
                @AlmondMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
                @JavaChips.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJavaChips;
                @JavaChips.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJavaChips;
                @JavaChips.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJavaChips;
                @Sprinkles.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprinkles;
                @Sprinkles.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprinkles;
                @Sprinkles.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprinkles;
                @Cinnamon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCinnamon;
                @Cinnamon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCinnamon;
                @Cinnamon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCinnamon;
                @CaramelDrizzle.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramelDrizzle;
                @CaramelDrizzle.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramelDrizzle;
                @CaramelDrizzle.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramelDrizzle;
                @Cherry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCherry;
                @Cherry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCherry;
                @Cherry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCherry;
                @Frappucino.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrappucino;
                @Frappucino.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrappucino;
                @Frappucino.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFrappucino;
                @Hot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHot;
                @Hot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHot;
                @Hot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHot;
                @Iced.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIced;
                @Iced.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIced;
                @Iced.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIced;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Blend.started += instance.OnBlend;
                @Blend.performed += instance.OnBlend;
                @Blend.canceled += instance.OnBlend;
                @Shake.started += instance.OnShake;
                @Shake.performed += instance.OnShake;
                @Shake.canceled += instance.OnShake;
                @Stir.started += instance.OnStir;
                @Stir.performed += instance.OnStir;
                @Stir.canceled += instance.OnStir;
                @Ice.started += instance.OnIce;
                @Ice.performed += instance.OnIce;
                @Ice.canceled += instance.OnIce;
                @Espresso.started += instance.OnEspresso;
                @Espresso.performed += instance.OnEspresso;
                @Espresso.canceled += instance.OnEspresso;
                @Caramel.started += instance.OnCaramel;
                @Caramel.performed += instance.OnCaramel;
                @Caramel.canceled += instance.OnCaramel;
                @Vanilla.started += instance.OnVanilla;
                @Vanilla.performed += instance.OnVanilla;
                @Vanilla.canceled += instance.OnVanilla;
                @Peppermint.started += instance.OnPeppermint;
                @Peppermint.performed += instance.OnPeppermint;
                @Peppermint.canceled += instance.OnPeppermint;
                @Hazelnut.started += instance.OnHazelnut;
                @Hazelnut.performed += instance.OnHazelnut;
                @Hazelnut.canceled += instance.OnHazelnut;
                @Mocha.started += instance.OnMocha;
                @Mocha.performed += instance.OnMocha;
                @Mocha.canceled += instance.OnMocha;
                @BlackTea.started += instance.OnBlackTea;
                @BlackTea.performed += instance.OnBlackTea;
                @BlackTea.canceled += instance.OnBlackTea;
                @GreenTea.started += instance.OnGreenTea;
                @GreenTea.performed += instance.OnGreenTea;
                @GreenTea.canceled += instance.OnGreenTea;
                @ChaiTea.started += instance.OnChaiTea;
                @ChaiTea.performed += instance.OnChaiTea;
                @ChaiTea.canceled += instance.OnChaiTea;
                @PassionTea.started += instance.OnPassionTea;
                @PassionTea.performed += instance.OnPassionTea;
                @PassionTea.canceled += instance.OnPassionTea;
                @Matcha.started += instance.OnMatcha;
                @Matcha.performed += instance.OnMatcha;
                @Matcha.canceled += instance.OnMatcha;
                @WhippedCream.started += instance.OnWhippedCream;
                @WhippedCream.performed += instance.OnWhippedCream;
                @WhippedCream.canceled += instance.OnWhippedCream;
                @CremeBase.started += instance.OnCremeBase;
                @CremeBase.performed += instance.OnCremeBase;
                @CremeBase.canceled += instance.OnCremeBase;
                @CoffeeBase.started += instance.OnCoffeeBase;
                @CoffeeBase.performed += instance.OnCoffeeBase;
                @CoffeeBase.canceled += instance.OnCoffeeBase;
                @WholeMilk.started += instance.OnWholeMilk;
                @WholeMilk.performed += instance.OnWholeMilk;
                @WholeMilk.canceled += instance.OnWholeMilk;
                @SkimMilk.started += instance.OnSkimMilk;
                @SkimMilk.performed += instance.OnSkimMilk;
                @SkimMilk.canceled += instance.OnSkimMilk;
                @OatMilk.started += instance.OnOatMilk;
                @OatMilk.performed += instance.OnOatMilk;
                @OatMilk.canceled += instance.OnOatMilk;
                @AlmondMilk.started += instance.OnAlmondMilk;
                @AlmondMilk.performed += instance.OnAlmondMilk;
                @AlmondMilk.canceled += instance.OnAlmondMilk;
                @JavaChips.started += instance.OnJavaChips;
                @JavaChips.performed += instance.OnJavaChips;
                @JavaChips.canceled += instance.OnJavaChips;
                @Sprinkles.started += instance.OnSprinkles;
                @Sprinkles.performed += instance.OnSprinkles;
                @Sprinkles.canceled += instance.OnSprinkles;
                @Cinnamon.started += instance.OnCinnamon;
                @Cinnamon.performed += instance.OnCinnamon;
                @Cinnamon.canceled += instance.OnCinnamon;
                @CaramelDrizzle.started += instance.OnCaramelDrizzle;
                @CaramelDrizzle.performed += instance.OnCaramelDrizzle;
                @CaramelDrizzle.canceled += instance.OnCaramelDrizzle;
                @Cherry.started += instance.OnCherry;
                @Cherry.performed += instance.OnCherry;
                @Cherry.canceled += instance.OnCherry;
                @Frappucino.started += instance.OnFrappucino;
                @Frappucino.performed += instance.OnFrappucino;
                @Frappucino.canceled += instance.OnFrappucino;
                @Hot.started += instance.OnHot;
                @Hot.performed += instance.OnHot;
                @Hot.canceled += instance.OnHot;
                @Iced.started += instance.OnIced;
                @Iced.performed += instance.OnIced;
                @Iced.canceled += instance.OnIced;
            }
        }
    }
    public PlayerActions @player => new PlayerActions(this);
    private int m_keyboardandmouseSchemeIndex = -1;
    public InputControlScheme keyboardandmouseScheme
    {
        get
        {
            if (m_keyboardandmouseSchemeIndex == -1) m_keyboardandmouseSchemeIndex = asset.FindControlSchemeIndex("keyboard and mouse");
            return asset.controlSchemes[m_keyboardandmouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnStart(InputAction.CallbackContext context);
        void OnBlend(InputAction.CallbackContext context);
        void OnShake(InputAction.CallbackContext context);
        void OnStir(InputAction.CallbackContext context);
        void OnIce(InputAction.CallbackContext context);
        void OnEspresso(InputAction.CallbackContext context);
        void OnCaramel(InputAction.CallbackContext context);
        void OnVanilla(InputAction.CallbackContext context);
        void OnPeppermint(InputAction.CallbackContext context);
        void OnHazelnut(InputAction.CallbackContext context);
        void OnMocha(InputAction.CallbackContext context);
        void OnBlackTea(InputAction.CallbackContext context);
        void OnGreenTea(InputAction.CallbackContext context);
        void OnChaiTea(InputAction.CallbackContext context);
        void OnPassionTea(InputAction.CallbackContext context);
        void OnMatcha(InputAction.CallbackContext context);
        void OnWhippedCream(InputAction.CallbackContext context);
        void OnCremeBase(InputAction.CallbackContext context);
        void OnCoffeeBase(InputAction.CallbackContext context);
        void OnWholeMilk(InputAction.CallbackContext context);
        void OnSkimMilk(InputAction.CallbackContext context);
        void OnOatMilk(InputAction.CallbackContext context);
        void OnAlmondMilk(InputAction.CallbackContext context);
        void OnJavaChips(InputAction.CallbackContext context);
        void OnSprinkles(InputAction.CallbackContext context);
        void OnCinnamon(InputAction.CallbackContext context);
        void OnCaramelDrizzle(InputAction.CallbackContext context);
        void OnCherry(InputAction.CallbackContext context);
        void OnFrappucino(InputAction.CallbackContext context);
        void OnHot(InputAction.CallbackContext context);
        void OnIced(InputAction.CallbackContext context);
    }
}
