//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Gym/Gym.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Gym : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Gym()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Gym"",
    ""maps"": [
        {
            ""name"": ""GymActions"",
            ""id"": ""8a41c21a-e481-4b23-8fcd-a65ee1d1bc9a"",
            ""actions"": [
                {
                    ""name"": ""Lift"",
                    ""type"": ""Button"",
                    ""id"": ""c125d3b6-87fc-4145-9d5d-8f51faac597e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jab"",
                    ""type"": ""Button"",
                    ""id"": ""5b1e4153-f78a-459c-b4cb-59201827f09a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cross"",
                    ""type"": ""Button"",
                    ""id"": ""f5e7be43-3b75-480b-864c-0382927c1781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pushup"",
                    ""type"": ""Button"",
                    ""id"": ""502cb47d-7aff-4ef4-850a-48237a0f5aab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d513460-6442-4f4d-8e8c-1d37fe4f1ff0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05398b12-8ab2-42bd-94f1-29b64a0bfda6"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f8682ee-8beb-49c7-a7be-b87854087508"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3359767b-24a3-4c91-be1c-7e3ba8405936"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f092b07f-732b-479c-a60a-5353dde99aac"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b37e3715-636d-4c83-91cd-a7a672c060b0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78cf159a-6214-4bc1-946d-a6f7b108f9bc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce8a7187-5fc0-4ef4-b3a9-757c6623685e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pushup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6316c836-ece4-4b92-b68d-70c8a3e559a5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pushup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67f42a8d-f46c-4d7d-95b8-2184c9408d31"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pushup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GymActions
        m_GymActions = asset.FindActionMap("GymActions", throwIfNotFound: true);
        m_GymActions_Lift = m_GymActions.FindAction("Lift", throwIfNotFound: true);
        m_GymActions_Jab = m_GymActions.FindAction("Jab", throwIfNotFound: true);
        m_GymActions_Cross = m_GymActions.FindAction("Cross", throwIfNotFound: true);
        m_GymActions_Pushup = m_GymActions.FindAction("Pushup", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GymActions
    private readonly InputActionMap m_GymActions;
    private IGymActionsActions m_GymActionsActionsCallbackInterface;
    private readonly InputAction m_GymActions_Lift;
    private readonly InputAction m_GymActions_Jab;
    private readonly InputAction m_GymActions_Cross;
    private readonly InputAction m_GymActions_Pushup;
    public struct GymActionsActions
    {
        private @Gym m_Wrapper;
        public GymActionsActions(@Gym wrapper) { m_Wrapper = wrapper; }
        public InputAction @Lift => m_Wrapper.m_GymActions_Lift;
        public InputAction @Jab => m_Wrapper.m_GymActions_Jab;
        public InputAction @Cross => m_Wrapper.m_GymActions_Cross;
        public InputAction @Pushup => m_Wrapper.m_GymActions_Pushup;
        public InputActionMap Get() { return m_Wrapper.m_GymActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GymActionsActions set) { return set.Get(); }
        public void SetCallbacks(IGymActionsActions instance)
        {
            if (m_Wrapper.m_GymActionsActionsCallbackInterface != null)
            {
                @Lift.started -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnLift;
                @Lift.performed -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnLift;
                @Lift.canceled -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnLift;
                @Jab.started -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnJab;
                @Jab.performed -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnJab;
                @Jab.canceled -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnJab;
                @Cross.started -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnCross;
                @Cross.performed -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnCross;
                @Cross.canceled -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnCross;
                @Pushup.started -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnPushup;
                @Pushup.performed -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnPushup;
                @Pushup.canceled -= m_Wrapper.m_GymActionsActionsCallbackInterface.OnPushup;
            }
            m_Wrapper.m_GymActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Lift.started += instance.OnLift;
                @Lift.performed += instance.OnLift;
                @Lift.canceled += instance.OnLift;
                @Jab.started += instance.OnJab;
                @Jab.performed += instance.OnJab;
                @Jab.canceled += instance.OnJab;
                @Cross.started += instance.OnCross;
                @Cross.performed += instance.OnCross;
                @Cross.canceled += instance.OnCross;
                @Pushup.started += instance.OnPushup;
                @Pushup.performed += instance.OnPushup;
                @Pushup.canceled += instance.OnPushup;
            }
        }
    }
    public GymActionsActions @GymActions => new GymActionsActions(this);
    public interface IGymActionsActions
    {
        void OnLift(InputAction.CallbackContext context);
        void OnJab(InputAction.CallbackContext context);
        void OnCross(InputAction.CallbackContext context);
        void OnPushup(InputAction.CallbackContext context);
    }
}
