//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Cafe Minigame/Cafe.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Cafe : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Cafe()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Cafe"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""0b580d8c-4e13-4c76-b6a4-a4f9c8abbbd6"",
            ""actions"": [
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""f35bb4ee-79fa-4729-89ff-2f785a7fa004"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Blend"",
                    ""type"": ""Button"",
                    ""id"": ""3366854e-a489-47f0-9393-a439364b2fae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ice"",
                    ""type"": ""Button"",
                    ""id"": ""04b5fc49-6a2d-4035-a171-97bd3c39e32c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Espresso"",
                    ""type"": ""Button"",
                    ""id"": ""01b3c212-7906-487c-ba2e-56dbb43cd6ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Caramel"",
                    ""type"": ""Button"",
                    ""id"": ""79d00f09-20b5-4feb-9d06-ff44c18eaf28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Vanilla"",
                    ""type"": ""Button"",
                    ""id"": ""767f5717-902a-4c10-9eff-17ab860a8333"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Peppermint"",
                    ""type"": ""Button"",
                    ""id"": ""59b842f5-84a6-46c1-92c4-504ac1b805f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hazelnut"",
                    ""type"": ""Button"",
                    ""id"": ""68de73f4-5bfe-45a4-a973-afd97486223d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mocha"",
                    ""type"": ""Button"",
                    ""id"": ""575ce2fe-a152-41d5-a11a-d7fcec3b1ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Strawberry"",
                    ""type"": ""Button"",
                    ""id"": ""bacd307f-0454-4f6b-9ebe-b327cc2e3982"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Matcha"",
                    ""type"": ""Button"",
                    ""id"": ""11c137c6-0383-440c-93a6-f6fa91e34c99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Creme Base"",
                    ""type"": ""Button"",
                    ""id"": ""438e4c0c-26bf-4989-99f2-019c11646855"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Coffee Base"",
                    ""type"": ""Button"",
                    ""id"": ""082cf36c-46ce-43f2-b543-8f60c6c11990"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Whole Milk"",
                    ""type"": ""Button"",
                    ""id"": ""05f22354-1019-4a21-ba5f-f9b0e22cd27d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skim Milk"",
                    ""type"": ""Button"",
                    ""id"": ""bac2f0e6-8028-484a-a569-948e301dc1ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Oat Milk"",
                    ""type"": ""Button"",
                    ""id"": ""2df162be-2af4-467b-9daf-9dfce9261db4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Almond Milk"",
                    ""type"": ""Button"",
                    ""id"": ""50eede87-94f9-4db7-9edc-02e6463e9cd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""946a4ce3-0a9e-4a7d-a776-df4c91cc77b1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blend"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8312fa5f-a9ec-4fae-af9e-c2794fe0cda9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Ice"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12604d43-6bf2-49d5-bccb-59df383150a0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Espresso"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90d75569-55e7-422b-9991-d2d86ea0a04c"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Caramel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c95d7eea-1960-49af-b891-177ccd722a6c"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Vanilla"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73458179-b697-4162-ba50-4fff1138680a"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Peppermint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f4453fe-1cfc-46b6-b13e-d57ba7b9deb6"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Hazelnut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6763e27-1b9c-4dee-bfc0-2a2ce41dea32"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Mocha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcb6184d-aa77-4ef7-b76f-50ffac42dea1"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Strawberry"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db90c3cb-642e-4772-b0a7-53348ddd008b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Matcha"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a519e507-b741-4ed8-9654-0cd11bdd9ee0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Creme Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50dc7cd4-7e51-4358-a9de-dd22192b7650"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Coffee Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31de4424-e3f4-44b2-a477-5451cd29788b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Whole Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0954211-4d51-44ad-9e5b-435e3e235e01"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Skim Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4314379-8d2a-4147-8b33-9e3f04a360e0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Oat Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17730c3c-ffae-4260-8751-1629a7686043"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""keyboard and mouse"",
                    ""action"": ""Almond Milk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""545912fc-fa53-4513-a122-9b2d941f48a4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""keyboard and mouse"",
            ""bindingGroup"": ""keyboard and mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // player
        m_player = asset.FindActionMap("player", throwIfNotFound: true);
        m_player_Start = m_player.FindAction("Start", throwIfNotFound: true);
        m_player_Blend = m_player.FindAction("Blend", throwIfNotFound: true);
        m_player_Ice = m_player.FindAction("Ice", throwIfNotFound: true);
        m_player_Espresso = m_player.FindAction("Espresso", throwIfNotFound: true);
        m_player_Caramel = m_player.FindAction("Caramel", throwIfNotFound: true);
        m_player_Vanilla = m_player.FindAction("Vanilla", throwIfNotFound: true);
        m_player_Peppermint = m_player.FindAction("Peppermint", throwIfNotFound: true);
        m_player_Hazelnut = m_player.FindAction("Hazelnut", throwIfNotFound: true);
        m_player_Mocha = m_player.FindAction("Mocha", throwIfNotFound: true);
        m_player_Strawberry = m_player.FindAction("Strawberry", throwIfNotFound: true);
        m_player_Matcha = m_player.FindAction("Matcha", throwIfNotFound: true);
        m_player_CremeBase = m_player.FindAction("Creme Base", throwIfNotFound: true);
        m_player_CoffeeBase = m_player.FindAction("Coffee Base", throwIfNotFound: true);
        m_player_WholeMilk = m_player.FindAction("Whole Milk", throwIfNotFound: true);
        m_player_SkimMilk = m_player.FindAction("Skim Milk", throwIfNotFound: true);
        m_player_OatMilk = m_player.FindAction("Oat Milk", throwIfNotFound: true);
        m_player_AlmondMilk = m_player.FindAction("Almond Milk", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player
    private readonly InputActionMap m_player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_player_Start;
    private readonly InputAction m_player_Blend;
    private readonly InputAction m_player_Ice;
    private readonly InputAction m_player_Espresso;
    private readonly InputAction m_player_Caramel;
    private readonly InputAction m_player_Vanilla;
    private readonly InputAction m_player_Peppermint;
    private readonly InputAction m_player_Hazelnut;
    private readonly InputAction m_player_Mocha;
    private readonly InputAction m_player_Strawberry;
    private readonly InputAction m_player_Matcha;
    private readonly InputAction m_player_CremeBase;
    private readonly InputAction m_player_CoffeeBase;
    private readonly InputAction m_player_WholeMilk;
    private readonly InputAction m_player_SkimMilk;
    private readonly InputAction m_player_OatMilk;
    private readonly InputAction m_player_AlmondMilk;
    public struct PlayerActions
    {
        private @Cafe m_Wrapper;
        public PlayerActions(@Cafe wrapper) { m_Wrapper = wrapper; }
        public InputAction @Start => m_Wrapper.m_player_Start;
        public InputAction @Blend => m_Wrapper.m_player_Blend;
        public InputAction @Ice => m_Wrapper.m_player_Ice;
        public InputAction @Espresso => m_Wrapper.m_player_Espresso;
        public InputAction @Caramel => m_Wrapper.m_player_Caramel;
        public InputAction @Vanilla => m_Wrapper.m_player_Vanilla;
        public InputAction @Peppermint => m_Wrapper.m_player_Peppermint;
        public InputAction @Hazelnut => m_Wrapper.m_player_Hazelnut;
        public InputAction @Mocha => m_Wrapper.m_player_Mocha;
        public InputAction @Strawberry => m_Wrapper.m_player_Strawberry;
        public InputAction @Matcha => m_Wrapper.m_player_Matcha;
        public InputAction @CremeBase => m_Wrapper.m_player_CremeBase;
        public InputAction @CoffeeBase => m_Wrapper.m_player_CoffeeBase;
        public InputAction @WholeMilk => m_Wrapper.m_player_WholeMilk;
        public InputAction @SkimMilk => m_Wrapper.m_player_SkimMilk;
        public InputAction @OatMilk => m_Wrapper.m_player_OatMilk;
        public InputAction @AlmondMilk => m_Wrapper.m_player_AlmondMilk;
        public InputActionMap Get() { return m_Wrapper.m_player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Start.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStart;
                @Blend.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Blend.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Blend.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlend;
                @Ice.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Ice.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Ice.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnIce;
                @Espresso.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Espresso.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Espresso.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEspresso;
                @Caramel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Caramel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Caramel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCaramel;
                @Vanilla.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Vanilla.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Vanilla.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVanilla;
                @Peppermint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Peppermint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Peppermint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPeppermint;
                @Hazelnut.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Hazelnut.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Hazelnut.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHazelnut;
                @Mocha.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @Mocha.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @Mocha.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMocha;
                @Strawberry.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStrawberry;
                @Strawberry.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStrawberry;
                @Strawberry.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStrawberry;
                @Matcha.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @Matcha.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @Matcha.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMatcha;
                @CremeBase.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CremeBase.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CremeBase.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCremeBase;
                @CoffeeBase.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @CoffeeBase.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @CoffeeBase.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCoffeeBase;
                @WholeMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @WholeMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @WholeMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWholeMilk;
                @SkimMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @SkimMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @SkimMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkimMilk;
                @OatMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @OatMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @OatMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOatMilk;
                @AlmondMilk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
                @AlmondMilk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
                @AlmondMilk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAlmondMilk;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Blend.started += instance.OnBlend;
                @Blend.performed += instance.OnBlend;
                @Blend.canceled += instance.OnBlend;
                @Ice.started += instance.OnIce;
                @Ice.performed += instance.OnIce;
                @Ice.canceled += instance.OnIce;
                @Espresso.started += instance.OnEspresso;
                @Espresso.performed += instance.OnEspresso;
                @Espresso.canceled += instance.OnEspresso;
                @Caramel.started += instance.OnCaramel;
                @Caramel.performed += instance.OnCaramel;
                @Caramel.canceled += instance.OnCaramel;
                @Vanilla.started += instance.OnVanilla;
                @Vanilla.performed += instance.OnVanilla;
                @Vanilla.canceled += instance.OnVanilla;
                @Peppermint.started += instance.OnPeppermint;
                @Peppermint.performed += instance.OnPeppermint;
                @Peppermint.canceled += instance.OnPeppermint;
                @Hazelnut.started += instance.OnHazelnut;
                @Hazelnut.performed += instance.OnHazelnut;
                @Hazelnut.canceled += instance.OnHazelnut;
                @Mocha.started += instance.OnMocha;
                @Mocha.performed += instance.OnMocha;
                @Mocha.canceled += instance.OnMocha;
                @Strawberry.started += instance.OnStrawberry;
                @Strawberry.performed += instance.OnStrawberry;
                @Strawberry.canceled += instance.OnStrawberry;
                @Matcha.started += instance.OnMatcha;
                @Matcha.performed += instance.OnMatcha;
                @Matcha.canceled += instance.OnMatcha;
                @CremeBase.started += instance.OnCremeBase;
                @CremeBase.performed += instance.OnCremeBase;
                @CremeBase.canceled += instance.OnCremeBase;
                @CoffeeBase.started += instance.OnCoffeeBase;
                @CoffeeBase.performed += instance.OnCoffeeBase;
                @CoffeeBase.canceled += instance.OnCoffeeBase;
                @WholeMilk.started += instance.OnWholeMilk;
                @WholeMilk.performed += instance.OnWholeMilk;
                @WholeMilk.canceled += instance.OnWholeMilk;
                @SkimMilk.started += instance.OnSkimMilk;
                @SkimMilk.performed += instance.OnSkimMilk;
                @SkimMilk.canceled += instance.OnSkimMilk;
                @OatMilk.started += instance.OnOatMilk;
                @OatMilk.performed += instance.OnOatMilk;
                @OatMilk.canceled += instance.OnOatMilk;
                @AlmondMilk.started += instance.OnAlmondMilk;
                @AlmondMilk.performed += instance.OnAlmondMilk;
                @AlmondMilk.canceled += instance.OnAlmondMilk;
            }
        }
    }
    public PlayerActions @player => new PlayerActions(this);
    private int m_keyboardandmouseSchemeIndex = -1;
    public InputControlScheme keyboardandmouseScheme
    {
        get
        {
            if (m_keyboardandmouseSchemeIndex == -1) m_keyboardandmouseSchemeIndex = asset.FindControlSchemeIndex("keyboard and mouse");
            return asset.controlSchemes[m_keyboardandmouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnStart(InputAction.CallbackContext context);
        void OnBlend(InputAction.CallbackContext context);
        void OnIce(InputAction.CallbackContext context);
        void OnEspresso(InputAction.CallbackContext context);
        void OnCaramel(InputAction.CallbackContext context);
        void OnVanilla(InputAction.CallbackContext context);
        void OnPeppermint(InputAction.CallbackContext context);
        void OnHazelnut(InputAction.CallbackContext context);
        void OnMocha(InputAction.CallbackContext context);
        void OnStrawberry(InputAction.CallbackContext context);
        void OnMatcha(InputAction.CallbackContext context);
        void OnCremeBase(InputAction.CallbackContext context);
        void OnCoffeeBase(InputAction.CallbackContext context);
        void OnWholeMilk(InputAction.CallbackContext context);
        void OnSkimMilk(InputAction.CallbackContext context);
        void OnOatMilk(InputAction.CallbackContext context);
        void OnAlmondMilk(InputAction.CallbackContext context);
    }
}
